window.BUILTIN_PROFILES = [
  {
    "name": "Digital7",
    "data": {
      "numericFont": "Digital7Mono",
      "alphaFont": "Digital7Mono",
      "colonFont": "Digital7Mono",
      "multiFont": false,
      "numericScale": 100,
      "alphaScale": 100,
      "colonScale": 100,
      "numericOffset": 0,
      "alphaOffset": 0,
      "colonOffset": 0,
      "weightGap": 0.14,
      "fr": 0.21,
      "dateColor": "#fb04ad",
      "timeColor": "#04fb62",
      "colonColor": "#04fb62",
      "inheritColonColor": true,
      "secColor": "#00aaff",
      "secFontFactor": 0.56,
      "secColonDistance": 0.08,
      "secOffset": 0,
      "sizeBudget": 0.97,
      "padHours": false,
      "recenterLeadingOne": true,
      "ntpServer": "",
      "sleepTimeout": 0
    }
  },
  {
    "name": "Automate",
    "data": {
      "numericFont": "Automate Light",
      "alphaFont": "Automate Light",
      "colonFont": "Automate Light",
      "multiFont": false,
      "numericScale": 100,
      "alphaScale": 100,
      "colonScale": 100,
      "numericOffset": 0,
      "alphaOffset": 0,
      "colonOffset": 0,
      "weightGap": 0.17,
      "fr": 0.23,
      "dateColor": "#fb04b9",
      "timeColor": "#4568f2",
      "colonColor": "#4568f2",
      "inheritColonColor": true,
      "secColor": "#24b742",
      "secFontFactor": 0.59,
      "secColonDistance": 0.08,
      "secOffset": 0,
      "sizeBudget": 0.92,
      "ntpServer": "",
      "sleepTimeout": 0
    }
  },
  {
    "name": "Automata Extra",
    "default": true,
    "data": {
      "numericFont": "Automata ExtraLight",
      "alphaFont": "Automata ExtraLight",
      "colonFont": "Automate Light",
      "multiFont": true,
      "numericScale": 100,
      "alphaScale": 100,
      "colonScale": 71,
      "numericOffset": 0,
      "alphaOffset": 0,
      "colonOffset": 0,
      "weightGap": 0.15,
      "fr": 0.23,
      "dateColor": "#fb04b9",
      "timeColor": "#4568f2",
      "colonColor": "#04fb62",
      "inheritColonColor": true,
      "secColor": "#24b742",
      "secFontFactor": 0.59,
      "secColonDistance": 0.08,
      "secOffset": 0,
      "sizeBudget": 0.92,
      "ntpServer": "",
      "sleepTimeout": 0,
      "dualFont": true
    }
  },
  {
    "name": "Matrix",
    "data": {
      "numericFont": "LCDDot",
      "alphaFont": "LCDDot",
      "colonFont": "LCDDot",
      "multiFont": false,
      "numericScale": 100,
      "alphaScale": 100,
      "colonScale": 100,
      "numericOffset": 0,
      "alphaOffset": 0,
      "colonOffset": 0,
      "weightGap": 0.1,
      "fr": 0.23,
      "dateColor": "#4de0bb",
      "timeColor": "#f72222",
      "colonColor": "#f72222",
      "inheritColonColor": true,
      "secColor": "#5d87ea",
      "secFontFactor": 0.59,
      "secColonDistance": 0.06,
      "secOffset": -0.2,
      "sizeBudget": 0.92,
      "ntpServer": "",
      "sleepTimeout": 0,
      "dualFont": false
    }
  },
  {
    "name": "Segment",
    "data": {
      "numericFont": "DSEG7Classic",
      "alphaFont": "DSEG14Classic",
      "colonFont": "DSEG7Classic",
      "multiFont": true,
      "numericScale": 100,
      "alphaScale": 100,
      "colonScale": 71,
      "numericOffset": 0,
      "alphaOffset": 0,
      "colonOffset": 0,
      "weightGap": 0.16,
      "fr": 0.23,
      "dateColor": "#fbe704",
      "timeColor": "#2b4ac5",
      "colonColor": "#04fb62",
      "inheritColonColor": true,
      "secColor": "#f72222",
      "secFontFactor": 0.59,
      "secColonDistance": 0.08,
      "secOffset": 0,
      "sizeBudget": 0.92,
      "ntpServer": "",
      "sleepTimeout": 0,
      "padHours": false,
      "recenterLeadingOne": true,
      "dualFont": true
    }
  },
];
